[package]
name = "matrixbot-rust"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.14"
anyhow = "1.0.43"
serde = "1.0.129"
serde_json = "1.0.66"
matrix-sdk = "0.3.0"
ruma = "0.2.0"
actix = "0.12.0"
actix-web = "3.3.2"
rocksdb = "0.17.0"
uuid = { version = "0.8.2", features = [ "v4", "serde" ] }
url = "2.2.2"
async-trait = "0.1.51"