database:
  uri: mongodb://localhost:27017
  name: matrixbot
listener: 127.0.0.1:8000
escalation:
  enabled: true
  config:
    escalation_window: 3600 # one hour
adapter:
  - name: matrix
    enabled: false
    escalation:
      enabled: false
      acks:
        min_role: mods
    config:
      homeserver: https://matrix.org
      username: username
      password: password
      db_path: db/matrix.db
      device_name: matrixbot-ack
      device_id: matrixbot-some-id
      ecalation_levels:
      - "!abcdef:matrix.org"
      - "!ghijkl:matrix.org"
  - name: pager_duty
    enabled: false
    escalation:
      enabled: true
      acks:
        users:
        - bob
    config:
      api_key: abcdefg
      payload_source: "Matrixbot Ack Service"
      ecalation_levels:
      - integration_key: ABC
        # Possible values: critical, error, warning, info
        payload_severity: warning
      - integration_key: XYZ
        payload_severity: critical

users:
- name: alice
  email: alice@email.com
  matrix: '@alice:matrix.org'
  pagerduty: alice@email.com
- name: bob
  email: bob@email.com
  matrix: '@bob:matrix.org'
  pagerduty: bob@email.com
- name: dave
  email: dave@email.com
  matrix: '@dave:matrix.org'
  pagerduty: dave@email.com

roles:
- name: mods
  members:
  - alice
- name: admins
  members:
  - bob
  - dave