database:
  uri: mongodb://localhost:27017
  name: matrixbot
listener: 127.0.0.1:8000
escalation:
  enabled: true
  config:
    escalation_window: 3600 # one hour
adapter:
  matrix:
    enabled: false
    # Overwrites the 'escalation' above.
    escalation:
      enabled: false
    config:
      homeserver: https://matrix.org
      username: username
      password: password
      db_path: db/matrix.db
      device_name: matrixbot-ack
      device_id: matrixbot-some-id
      ecalation_levels:
      - "!abcdef:matrix.org"
      - "!ghijkl:matrix.org"
  pager_duty:
    enabled: false
    config:
      api_key: abcdefg
      payload_source: "Matrixbot Ack Service"
      ecalation_levels:
      - integration_key: ABC
        # Possible values: critical, error, warning, info
        payload_severity: warning
      - integration_key: XYZ
        payload_severity: critical
