database:
  uri: mongodb://localhost:27017
  name: matrixbot
listener: 127.0.0.1:8000
escalation:
  window: 3600 # one hour
adapter:
  matrix:
    enabled: false
    levels:
    - "!abcdef:matrix.org"
    - "!ghijkl:matrix.org"
    config:
      homeserver: https://matrix.org
      username: username
      password: password
      db_path: db/matrix.db
      device_name: matrixbot-ack
      device_id: matrixbot-some-id
  pager_duty:
    enabled: false
    levels:
    - integration_key: ABC
      # Possible values: critical, error, warning, info
      payload_severity: warning
    - integration_key: XYZ
      payload_severity: critical
    config:
      api_key: abcdefg
      payload_source: "Matrixbot Ack Service"
  email:
    enabled: false
    levels:
    - "alice@email.com"
    - "bob@email.com"
    - "dave@email.com"
    config:
      # TODO
