apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}  
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
          - -c
          - "/app/config/config.yaml"
          volumeMounts:
          - name: config
            mountPath: /app/config
          ports:
          - name: http
            containerPort: 8000
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 8000
            initialDelaySeconds: 10
            timeoutSeconds: 200
          {{ if ne .Values.environment "ci" }}  
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{ end }}  
      volumes:
      - name: config
        configMap:
          name: {{ .Release.Name }}
