environment: production

image:
  repository: web3f/matrixbot-ack
  tag: v0.1.3
  pullPolicy: IfNotPresent

config:
  db_path: '/app/db/matrixbot.db'
  matrix:
    homeserver: homeserver
    username: user
    password: password
    db_path: '/app/db/matrix.db'
    device_name: device_name
    device_id: device_id
  listener: 0.0.0.0:8000
  escalation_window: 60
  rooms:
    - "!abcdefg:matrix.org"
    - "!hijklmn:matrix.org"

resources:
  requests:
    cpu: "50m"
    memory: "50Mi"
  limits:
    cpu: "150m"
    memory: "150Mi"
