environments:
  production:
  ci:
  local:

repositories:
- name: w3f
  url: https://w3f.github.io/helm-charts/

releases:
- name: matrixbot-finance
  namespace: matrixbot-finance
  chart: ../charts/matrixbot_finance
  values:
    - ./config/matrixbot_finance.yaml.gotmpl
