environments:
  ci:
  local:

repositories:
- name: w3f
  url: https://w3f.github.io/helm-charts/

releases:
- name: matrixbot-ack
  chart: ../charts/matrixbot-ack
  values:
    - ./config/matrixbot-ack.yaml.gotmpl
