environments:
  ci:
  local:
repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
releases:
  - name: mongodb
    chart: bitnami/mongodb
    version: 10.27.2
    values:
      - ./config/mongodb.yaml.gotmpl
