environments:
  production:

repositories:
- name: w3f
  url: https://w3f.github.io/helm-charts/

releases:
- name: mongo-express
  namespace: registrar-v2
  chart: w3f/mongo-express
  version: v0.1.0
  values:
  - ./config/mongo-express.yaml.gotmpl
