environment: production

image:
  repository: web3f/matrixbot-finance
  tag: v0.1.2
  pullPolicy: Always

config:
  db_path: '/app/db/matrixbot.db'
  matrix:
    homeserver: homeserver
    username: user
    password: password
    db_path: '/app/db/matrix.db'
    device_name: device_name
    device_id: device_id
  listener: 127.0.0.1:8000
  escalation_window: 60
  rooms:
    - "!abcdefg:matrix.org"
    - "!hijklmn:matrix.org"

resources:
  requests:
    cpu: "300m"
    memory: "500Mi"
  limits:
    cpu: "500m"
    memory: "700Mi"
