apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
          - name: config
            mountPath: /app
          - name: db
            mountPath: "/app/{{ .Values.config.db_path }}"
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 8000
            initialDelaySeconds: 10
            timeoutSeconds: 200
      volumes:
      - name: config
        configMap:
          name: {{ .Release.Name }}
      - name: db
        {{ if and (ne .Values.environment "ci") (ne .Values.environment "local") }}
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-db
        {{ else }}
        emptyDir: {}
        {{ end }}
